version: '3.9'

services:
  evm-node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evm-node
    ports:
      - "26656:26656"
      - "26657:26657"
      - "1317:1317"
      - "8545:8545"
      - "8546:8546"
    volumes:
      - ./data:/root/.ethermintd  # Fixed path to match logs
    networks:
      - evm-network
    restart: always
    environment:
      - EVM_CHAIN_ID=9000  # Add chain ID as environment variable

  evm-db:
    image: postgres:13.20  # Use specific version from logs
    container_name: evm-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blockscout
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - evm-network
    restart: always
    mem_limit: 1g

  redis-db:
    image: redis:7.4.2  # Use version from logs
    container_name: redis-db
    command: redis-server --save 60 1 --appendonly yes --requirepass your_redis_password  # Add password
    volumes:
      - ./redis-data:/data
    networks:
      - evm-network
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: blockscout/blockscout:7.0.2  # Match version from logs
    container_name: backend
    depends_on:
      - evm-db
      - redis-db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@evm-db:5432/blockscout?ssl=false
      - ETHEREUM_JSONRPC_HTTP_URL=http://evm-node:8545
      - ETHEREUM_JSONRPC_WS_URL=ws://evm-node:8546
      - SECRET_KEY_BASE=your_actual_secret_key_base
      - CHAIN_ID=9000
      - REDIS_URL=redis://:your_redis_password@redis-db:6379
      - MIX_ENV=prod
    networks:
      - evm-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    image: blockscout/frontend:latest
    container_name: frontend
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4000
      - NEXT_PUBLIC_NETWORK_NAME=Ethermint
      - NEXT_PUBLIC_NETWORK_ICON=/icon.png
      - NEXT_PUBLIC_NETWORK_LOGO=/logo.png
    networks:
      - evm-network
    restart: unless-stopped

  proxy:
    image: nginx:1.27.4  # Match version from logs
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./templates:/etc/nginx/templates
    depends_on:
      - backend
      - frontend
    networks:
      - evm-network
    restart: always

networks:
  evm-network:
    driver: bridge