name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      # Set default values if not already provided by your repo/.env
      KEY_NAME: "my-key"
      CHAIN_ID: "evmos_9001-2"

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Clone upstream repository
        run: |
          git clone https://github.com/evmos/evmos.git
          ls -la

      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build -t evmos -f Dockerfile evmos/ --no-cache

      - name: Check evmosd version
        run: |
          docker run --rm evmos evmosd version

      - name: Run container
        run: |
          docker run -d --name evmos-test -p 8545:8545 evmos
          # Allow time for the node to start and expose JSON-RPC endpoint
          sleep 15

      - name: Run RPC and TX tests
        run: |
          # List wallet addresses via JSON-RPC
          echo "Listing wallet addresses via JSON-RPC..."
          RPC_ACCOUNTS=$(curl -s -X POST http://localhost:8545 -H "Content-Type: application/json" \
              --data '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":1}' | jq -r '.result')
          echo "JSON-RPC Accounts: $RPC_ACCOUNTS"
          # Import a new key using a unique key name to avoid duplication error
          NEW_MNEMONIC="test test test test test test test test test test test junk"
          TEST_KEY="test-key-$(date +%s)"
          echo "Importing new key '$TEST_KEY'..."
          # Import key by piping the mnemonic only
          printf "%s\n" "$NEW_MNEMONIC" | docker exec -i evmos-test evmosd keys add "$TEST_KEY" --recover --keyring-backend=test --output=json
          NEW_ADDR=$(docker exec evmos-test evmosd keys show "$TEST_KEY" -a --keyring-backend=test)
          echo "New account address: $NEW_ADDR"
          # List balances of the new account BEFORE sending funds
          echo "Balances of new account BEFORE transaction:"
          docker exec evmos-test evmosd query bank balances "$NEW_ADDR" --output json || true
          # Get sender address (the default key) – adjust the key name if needed
          SENDER=$(docker exec evmos-test evmosd keys show "$KEY_NAME" -a --keyring-backend=test)
          echo "Sender address: $SENDER"
          # Send 1aevmos from sender to the new account
          echo "Sending 1aevmos from sender to new account..."
          docker exec evmos-test evmosd tx bank send "$SENDER" "$NEW_ADDR" 1aevmos --chain-id "$CHAIN_ID" --keyring-backend=test --yes
          # Wait for the transaction to be processed
          sleep 10
          # Query the new account balance AFTER the transaction
          echo "Balances of new account AFTER transaction:"
          docker exec evmos-test evmosd query bank balances "$NEW_ADDR" --output json