name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Clone upstream repository
        run: |
          git clone https://github.com/evmos/evmos.git
          ls -la

      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build -t evmos -f Dockerfile evmos/ --no-cache

      - name: Check evmosd version
        run: |
          docker run --rm evmos evmosd version

      - name: Run container and test JSON-RPC health check
        run: |
          # Start the container in detached mode
          docker run -d --name evmos-test -p 8545:8545 evmos
          # Wait for the node to start and expose JSON-RPC endpoint
          sleep 15
          # Check that JSON-RPC endpoint responds (adjust URL/path as needed)
          curl --fail http://localhost:8545 || (docker logs evmos-test && exit 1)
          docker stop evmos-test