name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      # Set default values if not already provided by your repo/.env
      KEY_NAME: "my-key"
      CHAIN_ID: "evmos_9001-2"

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Clone upstream repository
        run: |
          git clone https://github.com/evmos/evmos.git
          ls -la

      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build -t evmos -f Dockerfile evmos/ --no-cache

      - name: Check evmosd version
        run: |
          docker run --rm evmos evmosd version

      - name: Run container
        run: |
          docker run -d --name evmos-test -p 8545:8545 evmos
          # Allow time for the node to start and expose JSON-RPC endpoint
          sleep 15

